# Generated by Django 4.0 on 2026-06-05 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='USER',
        ),
    ]
